import * as React from "react"
import Layout from "../components/layout"
import Seo from "../components/seo"

const CompetitionPage = () => (
  <Layout>
    <div className="text-slate">
      <h1 className="text-5xl font-axel p-10 pl-0 pb-5">Competition</h1>
      <h2 className="text-light-slate italic">Terms and Conditions</h2>    
      <p>These Terms and Conditions prevail in the event of any conflict or inconsistency with any other communications, including advertising or promotional materials. Entry/claim instructions are deemed to form part of the terms and conditions and by participating all claimants will be deemed to have accepted and be bound by the terms and conditions. Please retain a copy for your information.</p>
      <p>Eligibility: This prize promotion is open to UK residents (England, Scotland, Wales and Northern Ireland) aged 18 years or over.</p>
      <p>Promotional Period: Please see each individual promotion for its prize pool.</p>
      <p>Entry Instructions: Please see the individual prize promotion for entry details.</p>
      <p>Only one entry per person per prize promotion unless otherwise stated in the individual promotion.</p>
      <p>Any entries that the Promoter consider (in our absolute discretion) to be dangerous, vulgar, offensive, indecent, illegal racist, copied, offensive, cruel or fraudulent, or infringe on the rights or copyright of others will be immediately disqualified.</p>
      <p>No third party or bulk entries. If it becomes apparent that either a participant or household is using any means to circumvent this condition such as, and without limitation, multiple email accounts, multiple reproduced or computer-generated entries, using multiple identities, fraudulently falsifying data, acting fraudulently or dishonestly in the opinion of the promoter or otherwise acting in violation of these terms, these participants will be disqualified, and any prize entitlement will be void.</p>
      <p>Incomplete, illegible, misdirected or late entries will not be accepted. Proof of sending will not be accepted as proof of delivery or receipt. No responsibility can be accepted for entries that are incomplete, lost due to technical reasons, corrupted, delayed, wrongly delivered, or not received for whatsoever reason.</p>
      <p>Prize Fund: Please see each individual promotion for its prize pool.<br></br>Winner Selection: Prize draw winner (s)will be randomly selected by a computerised random generator from all entries. Skills based entries shall be judged based on the judging criteria, set out in the promotion, by a panel which shall include one judge independent to the Promoter.</p>
      <p>Winner Notification: The winners will be notified by email via the account provided at point of entry within 14 days of the closing date and will have 14 days from notification to claim their prize. If a winner does not claim their prize within this timeframe the promoter reserves the right to withdraw prize entitlement and will award the prize to a reserve drawn at the same time as the original.</p>
      <p>It is the responsibility of the entrant to provide correct, up-to-date details when entering the prize promotion and acceptance of the prize. The Promoter cannot be held responsible for winners failing to supply accurate information which affects prize acceptance or delivery of their prize.<br></br>General: Promoter’s decision is final and binding. No correspondence will be entered into. Entry implies acceptance of these terms and conditions.<br></br> Prizes must be accepted as offered by the named winner. There is no cash or alternative prizes, in whole or part. The prizes are not transferable and cannot be resold.</p>
      <p>The Promoter reserves the right to substitute a prize of equal or greater value should circumstances outside its control make this necessary.<br></br>The Promoter reserves the right to verify winners and ask for proof of identity, age and address and to withdraw prize entitlement where there are reasonable grounds to believe there has been a breach of these terms and conditions</p>
      <p>You agree that if you are a winner, you will take part in and co-operate fully with reasonable publicity and to the use of your name, photograph and any comments in such publicity without any fee being payable. By entering the Promotion, each entrant grants the Promoter a world-wide, perpetual, irrevocable, non-exclusive, transferable, royalty free and sub-licensable right and licence to use reproduce, modify, adapt, publish or display (in whole or in part) any intellectual property contained in the content of their entry, without royalty, payment or other compensation. Each Entrant agrees not to assert any moral rights in relation to such use and warrants that they have full authority to grant such rights.</p>
      <p>The Promoter reserves the right, at its sole discretion, to eliminate or disqualify any entries or entrants that it regards as being in breach of these terms and conditions or the spirit of the Promotion. Those who try to circumvent the entry process and/or entry instructions by any method, will be disqualified and any prize award will be void.</p>
      <p>Entry into the Promotion is at the entrant’s sole risk. To the extent permitted by law, neither the Promoter nor Supplier accept any responsibility for any damage, loss, liabilities, injury, costs, expenses or claims (whether in contract, tort or otherwise) suffered by entrants or any third parties arising out of or in connection with the Promotion and/or accepting a prize. The Promoter and Supplier further disclaim liability for any injury or damage to entrants or any other person relating to or resulting from participation with this Promotion save that nothing in these terms and conditions shall act to limit or exclude the Promoter and Supplier’s liability resulting from its negligence or fraud.</p>
      <p> If for any reason, the Promotion is not capable of running as planned for reasons (including but not limited to tampering, unauthorized intervention, fraud, technical failures or any other causes beyond the control of the Promoter which corrupt or affect the administration, security, fairness, integrity or proper conduct of this Promotion), the Promoter reserves the right (subject to any written directions given under applicable law) to disqualify any individual who tampers with the entry process and to cancel, terminate, modify or suspend the Promotion.</p>
      <p>If an act, omission, event or circumstance occurs which are beyond the reasonable control of the Promoter and which prevents the Promoter from complying with these terms and conditions the Promoter will not be liable for any failure to perform or delay in performing its obligation. The Promoter accepts no responsibility for system errors or other issues that may result in disruption to, lost, delayed or not received entries, winner notifications or prizes. The Promoter, the Supplier or its agencies will not be responsible for the non-inclusion of entries as a result of technical failures or otherwise, including any such failure which is within the control of The Promoter or its agencies.</p>
      <p>Where a prize is provided by a Supplier, the Promoter accepts no responsibility for inaccuracy of any prize description, and The Supplier is responsible for prize fulfilment.</p>
      <p>If any of these clauses should be determined to be illegal, invalid or otherwise unenforceable then it shall be severed and deleted from these Terms and Conditions and the remaining clauses shall survive and remain in full force and effect.</p>
      <p> The Promoter and the Supplier reserve the right to cancel, amend, withdraw, terminate or temporarily suspend this promotion in the event of any unforeseen circumstances or technical reason outside its reasonable control, with no liability to any entrants or third parties but will use all reasonable endeavours to avoid consumer disappointment.</p>
      <p>The decisions of the Promoter are final and binding in all matters relating to the Promotion and no correspondence will be entered into. The Promotion and these terms and conditions, and any disputes arising therefrom, shall be subject to English law and the exclusive jurisdiction of the English and Welsh Courts.</p>
      <p>Data Protection: Any personal information that entrants share with the Promoter will be kept secure and only used in line with these terms and conditions unless the entrant has opted in to future marketing from the Promoter and/or the Supplier. By entering the promotion, entrants agree that their information may be used by the Promoter to administer the promotion and winners consent to give their name and county for the winners’ list.</p>
    </div>
  </Layout>
)

export const Head = () => <Seo title="Competition" description="Competition T&Cs for Charlie Cooks Favourite Book" />

export default CompetitionPage
